### ISSUE TITLE
HIV Guidance Document - Add a Table of Contents

### ISSUE THREAD

**Issue by frankambrosio3** [pha4ge/pipeline-resources#40]
### :pushpin: Explain the Request
We would like a table of contents added to the HIV Guidance document with links to all sections.

### :books: Context
Currently the document is a bit difficult to navigate for a newer github user, so a table of contents would enhance accessibility.

### :chart_with_upwards_trend: Desired Contribution
A fork of the main PHA4GE repo including Markdown code adding a table of contents to the HIV Guidance Document.

### :information_source: Additional Information
https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/

**Comment by MarcNiebel** [comment]
This has been completed by @frankambrosio3 #55
