### ISSUE TITLE
HIV Guidance Document-Table mixup in R markdown

### ISSUE THREAD

**Issue by MarcNiebel** [pha4ge/pipeline-resources#42]
Potential sequencing strategies table is absent. It is currently being occupied by the subtyping tools table

**Comment by frankambrosio3** [comment]
Moved table 3 to where it belongs, and added table 2 to the approapriate place in the doc.

**Comment by frankambrosio3** [comment]
Resolved

**Comment by frankambrosio3** [comment]
Thanks Marc!
